require("mason").setup()
require("mason-lspconfig").setup({
    ensure_installed = {
        "lua_ls",
        "rust_analyzer",
        "clangd",
        "cmake",
        "gopls",
        "ts_ls",
        "zls",
        "html",
        "cssls",
        "emmet_ls",
        "tailwindcss",
        "jdtls",
        "pylsp",
        "asm_lsp",
    },
})
